import assert from 'node:assert/strict';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import pg from 'pg';
import { hash, initializePipeline } from '../db/index.mjs';
import { createPipelineStore } from '../jobs/pipeline.mjs';
import { createCatalogReader } from '../../web/lib/catalog-reader.ts';
import { resolveIdentity } from '../identity/index.ts';
import { normalizeTitleKey, normalizeCategoryKey } from '../normalize/identity.ts';
import { expectedProviderListingId } from '../../contracts/listing.ts';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pipelineConfig, runPipeline } from '../jobs/run.mjs';
import { createPostgresIdentityJudgmentCache } from '../jobs/identity-judgments.mjs';
import { createAmbiguousIdentityJudge } from '../identity/jev.ts';
import { createFilesystemRawStore } from '../raw/store.mjs';
import { createPipelineCatalog } from '../../web/lib/pipeline-catalog.node.ts';
import { emptyFilters } from '../../web/lib/types.ts';

test('pipeline CLI fails closed without an operation, explicit connection or previous pointer',()=>{
  assert.throws(()=>pipelineConfig([],{}),/Usage/);
  assert.throws(()=>pipelineConfig(['--collection','input.json','--raw-directory','raw'],{}),/Explicit PostgreSQL/);
  assert.throws(()=>pipelineConfig(['--collection','input.json','--raw-directory','raw','--publish'],{}),/expected-previous/);
});

const enabled=process.env.BIPLAN_PIPELINE_DB_TEST==='1';
test('real PostgreSQL pipeline: immutable replay, scoped changes, fencing, pinning, rollback and source invalidation',{skip:!enabled,timeout:120000},async t=>{
  const container='biplan-catalog-local',database='biplan_pipeline_rebuild';
  const docker=(args,input)=>execFileSync('docker',args,{input,encoding:'utf8',windowsHide:true}).trim();
  assert.equal(docker(['inspect','--format','{{index .Config.Labels "biplan.preparation"}}',container]),'catalog-enrichment-v1');
  const admin=sql=>docker(['exec','-i',container,'psql','-X','-qAt','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres'],sql);
  const exists=admin(`SELECT EXISTS(SELECT FROM pg_database WHERE datname='${database}');`);
  if(exists!=='t') admin(`CREATE DATABASE ${database}; COMMENT ON DATABASE ${database} IS 'biplan pipeline rebuild task local tests';`);
  assert.equal(admin(`SELECT shobj_description(oid,'pg_database') FROM pg_database WHERE datname='${database}';`),'biplan pipeline rebuild task local tests');
  const environment=JSON.parse(docker(['inspect','--format','{{json .Config.Env}}',container]));
  const password=environment.find(value=>value.startsWith('POSTGRES_PASSWORD=')).slice('POSTGRES_PASSWORD='.length);
  const pool=new pg.Pool({host:'127.0.0.1',port:15432,user:'postgres',password,database,max:4,statement_timeout:10000});
  t.after(()=>pool.end());
  await pool.query('DROP SCHEMA IF EXISTS biplan_pipeline CASCADE');
  assert.equal((await initializePipeline(pool)).applied,true);
  assert.equal((await initializePipeline(pool)).applied,false);
  const pipeline=createPipelineStore(pool),reader=createCatalogReader((sql,values)=>pool.query(sql,values));
  const judgmentCache=createPostgresIdentityJudgmentCache(pool);
  const identityLeft={listingId:'identity-a',provider:'biletix',providerSessionIds:['a'],url:'https://www.biletix.com/etkinlik/A/ISTANBUL/tr',title:'Akustik Gecesi',description:'Canlı akustik müzik.',category:'Konser',startsAt:'2027-01-01T18:00:00.000Z',city:'İstanbul',venue:{name:'Test Sahne',district:'Kadıköy'}};
  const identityRight={...identityLeft,listingId:'identity-b',provider:'bubilet',providerSessionIds:['b'],title:'Bir Akşam Akustik',url:'https://www.bubilet.com.tr/istanbul/etkinlik/test'};
  let offlineJudgments=0;
  const makeJudge=model=>createAmbiguousIdentityJudge({model,cache:judgmentCache,maxCalls:5,judge:async()=>{
    offlineJudgments++;return {outcome:'same_session',probability:0.99,confidence:0.98,probabilities:{same_session:0.99,different:0.005,insufficient_evidence:0.005},model,usage:{inputTokens:100,outputTokens:10}};
  }});
  const judge=makeJudge('jev-1.13.0');
  const firstJudgment=await judge.evaluate(identityLeft,identityRight,'v','v');
  assert.equal(firstJudgment.merge,false,'No calibration means no merge');
  await judge.evaluate(identityLeft,identityRight,'v','v');assert.equal(offlineJudgments,1);assert.equal(judge.ledger.cached,1);
  await makeJudge('jev-1.14.0').evaluate(identityLeft,identityRight,'v','v');assert.equal(offlineJudgments,2,'Pinned model changes invalidate judgment cache');
  await judge.evaluate(identityLeft,{...identityRight,description:'Changed source evidence'},'v','v');assert.equal(offlineJudgments,3,'Evidence changes invalidate judgment cache');
  assert.equal((await pool.query('SELECT count(*)::int n FROM biplan_pipeline.identity_judgments')).rows[0].n,3);
  await assert.rejects(judgmentCache.put({...firstJudgment.decision,judgment:{...firstJudgment.decision.judgment,confidence:0.9}}),/cache conflict/);
  assert.equal((await judgmentCache.get(firstJudgment.decision.key)).judgment.confidence,0.98);
  const blobs=new Map();
  const listing=(provider,id,title='Bir Konser',startsAt='2027-01-01T18:00:00.000Z',observedAt='2026-10-02T12:00:00.000Z')=>{
    const body=Buffer.from(JSON.stringify({provider,id,title,startsAt,observedAt})),sha256=hash(body);blobs.set(sha256,body);
    const host={biletix:'www.biletix.com',bubilet:'www.bubilet.com.tr',biletinial:'biletinial.com'}[provider];
    const value={contractVersion:'provider-listing.v1',listingId:'',provider,providerEventId:id,providerSessionIds:[id],url:`https://${host}/event/${id}`,title,description:'Canlı müzik konseri',category:'Konser',startsAt,timezoneEvidence:{kind:'explicit_offset',sourceValue:startsAt},venue:{name:'Moda Sahnesi',district:'Kadıköy'},tiers:[{price:500,currency:'TRY',availability:'available'}],availability:'available',observedAt,extractorVersion:'fixture-1',rawObjectRef:{sha256,key:`bodies/${sha256}.bin`,bytes:body.length},city:'İstanbul'};
    value.listingId=expectedProviderListingId(value);return value;
  };
  const a=listing('biletix','a'),b=listing('bubilet','b'),c=listing('biletinial','c','Başka Konser','2027-01-02T18:00:00.000Z');
  const envelope=(id,listings)=>({id,scope:'partial',horizon:null,inventory:listings.map(l=>l.url),listings,pages:listings.map(l=>({url:l.url,provider:l.provider,status:'verified',observedAt:l.observedAt,rawObjectSha256:l.rawObjectRef.sha256,listingIds:[l.listingId]})),collectorRevision:'test'});
  const raw={readRaw:ref=>blobs.get(ref.sha256)},options={resolveIdentity,normalizeTitleKey,normalizeCategoryKey,timeBudgetMs:60000};
  await assert.rejects(pipeline.ingestCollection(envelope('bad',[a]),{readRaw:()=>Buffer.from('wrong')}),/verification failed/);
  await pipeline.ingestCollection(envelope('first',[a,b,c]),raw);
  const prepared=await pipeline.prepareCollection('first',{...options,resolveIdentity:async input=>{
    // The wrapper explicitly handles optional judgment failure and preserves the
    // deterministic output; the pipeline itself does not hide mandatory errors.
    try {await Promise.reject(new Error('offline optional judgment unavailable'));} catch {return resolveIdentity(input);}
  }});
  assert.equal(prepared.complete,true);assert.equal(prepared.counts.normalize,3);assert.equal(prepared.counts.identity,2);
  await assert.rejects(pipeline.publish('first',{expectedPreviousId:null,processDeadlineAt:Date.now()+1000}),/publication process or lease budget/);
  await assert.rejects(pipeline.publish('first',{expectedPreviousId:null,leaseMs:1000}),/publication process or lease budget/);
  const first=await pipeline.publish('first',{expectedPreviousId:null});
  const pinned=await reader.pin(),catalog=await reader.read(pinned);
  assert.equal(pinned,first.publicationId);assert.equal(catalog.sessions.length,2);assert.equal(catalog.manifest.offerCount,3);assert.equal(catalog.manifest.scope,'partial');assert.equal(catalog.manifest.lexicalOnlyCount,2);
  const selected=catalog.sessions.map(s=>({sessionId:s.id,offerId:s.offers[0].id,offerRevisionId:s.offers[0].revisionId}));
  assert.ok((await reader.revalidate(pinned,selected,'2026-10-02T13:00:00.000Z')).every(x=>x.usable));
  const runtime=createPipelineCatalog({BIPLAN_PG_HOST:'127.0.0.1',BIPLAN_PG_PORT:'15432',BIPLAN_PG_DATABASE:database,BIPLAN_PG_USER:'postgres',BIPLAN_PG_PASSWORD:password});
  t.after(()=>runtime.close());
  const servingPin=await runtime.pin(new Date('2026-10-02T13:00:00.000Z'));
  assert.equal(servingPin.publicationId,pinned);assert.equal(await servingPin.availability(),true);
  assert.equal((await servingPin.candidates(emptyFilters)).length,2);
  assert.equal((await servingPin.catalogStatus()).eligible,2);
  const readiness=await runtime.readiness();assert.equal(readiness.publicationId,pinned);assert.equal(readiness.catalog.stored,2);assert.equal(typeof readiness.ready,'boolean');
  await pipeline.ingestCollection(envelope('same',[a,b,c]),raw);
  const same=await pipeline.prepareCollection('same',{...options,resolveIdentity:()=>{throw new Error('Unchanged identity must be reused');}});
  assert.deepEqual(same.counts,{normalize:0,offers:0,identity:0,search:0});
  assert.equal((await pipeline.publish('same',{expectedPreviousId:pinned})).publicationId,pinned);
  const changed=listing('biletinial','c','Değişen Konser','2027-01-02T18:00:00.000Z','2026-10-02T12:30:00.000Z');
  await pipeline.ingestCollection(envelope('changed',[a,b,changed]),raw);
  const interrupted=await pipeline.prepareCollection('changed',{...options,signal:AbortSignal.abort()});
  assert.equal(interrupted.complete,false);assert.equal(interrupted.processed,0);
  const bounded=await pipeline.prepareCollection('changed',{...options,maxJobs:1});
  assert.equal(bounded.complete,false);assert.equal(bounded.counts.normalize,1);
  const changedResult=await pipeline.prepareCollection('changed',options);
  assert.deepEqual(changedResult.counts,{normalize:0,offers:1,identity:1,search:1});
  await assert.rejects(pipeline.publish('changed',{expectedPreviousId:null}),/Active publication changed/);
  const second=await pipeline.publish('changed',{expectedPreviousId:pinned});
  assert.notEqual(second.publicationId,pinned);assert.deepEqual(await reader.read(pinned),catalog);
  assert.equal((await reader.read(second.publicationId)).sessions.length,2);
  const stale=await reader.revalidate(pinned,selected,'2026-10-02T13:00:00.000Z');
  assert.equal(stale.filter(row=>!row.usable).length,1);
  assert.equal(await servingPin.availability(),true);assert.equal((await servingPin.candidates(emptyFilters)).length,1,'Changed member removes its old canonical session from real runtime candidates');
  await assert.rejects(pipeline.rollback({publicationId:pinned,expectedPreviousId:null}),/Active publication changed/);
  await pipeline.rollback({publicationId:pinned,expectedPreviousId:second.publicationId});
  assert.equal(await reader.pin(),pinned);
  assert.equal((await pipeline.publish('changed',{expectedPreviousId:second.publicationId})).replayed,true);
  assert.equal(await reader.pin(),pinned,'replay must not reactivate a rolled-back publication');
  const extra={stage:'fence-test',subject:'one',inputHash:hash('one'),version:'1',input:{}};
  await pipeline.jobs.enqueue('first',extra);
  const claim=await pipeline.jobs.claim({collectionId:'first',stage:'fence-test',owner:'old',leaseMs:10000});
  assert.equal(await pipeline.jobs.claim({collectionId:'first',stage:'fence-test',owner:'blocked',leaseMs:10000}),null);
  await pool.query("UPDATE biplan_pipeline.jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=$1",[claim.id]);
  const reclaimed=await pipeline.jobs.claim({collectionId:'first',stage:'fence-test',owner:'new',leaseMs:10000});
  assert.equal(Number(reclaimed.fence),Number(claim.fence)+1);
  await assert.rejects(pipeline.jobs.complete(claim,{}),/stale/);
  await pipeline.jobs.complete(reclaimed,{done:true});
  const negative={id:'negative',scope:'partial',inventory:[a.url],listings:[],rawObjects:[a.rawObjectRef],pages:[{url:a.url,provider:a.provider,status:'failed',observedAt:'2026-10-02T14:00:00.000Z',rawObjectSha256:a.rawObjectRef.sha256,listingIds:[]}]};
  await pipeline.ingestCollection(negative,raw);
  await pipeline.prepareCollection('negative',options);
  await assert.rejects(pipeline.publish('negative',{expectedPreviousId:pinned}),/page integrity/);
  const firstOffer=catalog.sessions.flatMap(s=>s.offers.map(o=>({sessionId:s.id,offerId:o.id,offerRevisionId:o.revisionId,provider:o.provider}))).find(o=>o.provider==='biletix');
  assert.equal((await reader.revalidate(pinned,[firstOffer],'2026-10-02T14:30:00.000Z'))[0].usable,false);
  assert.equal(await servingPin.availability(),false);assert.equal((await servingPin.candidates(emptyFilters)).length,0);
  assert.equal((await servingPin.catalogStatus()).eligible,0,'Current status cannot come from immutable catalog cache');
  assert.equal((await pool.query('SELECT count(*)::int n FROM biplan_pipeline.job_attempts WHERE cost_microusd<>0')).rows[0].n,0);
  const cliListing=listing('bubilet','cli','CLI Konseri','2027-01-03T18:00:00.000Z','2026-10-02T15:00:00.000Z');
  const output=resolve(import.meta.dirname,'../../web/work/pipeline-rebuild-verification'),rawDirectory=resolve(output,'raw');
  await mkdir(resolve(rawDirectory,'bodies'),{recursive:true});
  await writeFile(resolve(rawDirectory,cliListing.rawObjectRef.key),blobs.get(cliListing.rawObjectRef.sha256));
  const file=resolve(output,'collection.json');await writeFile(file,JSON.stringify(envelope('cli',[cliListing])));
  const cli=await runPipeline(['--collection',file,'--raw-directory',rawDirectory,'--initialize','--publish','--expected-previous',pinned],{BIPLAN_PG_HOST:'127.0.0.1',BIPLAN_PG_PORT:'15432',BIPLAN_PG_DATABASE:database,BIPLAN_PG_USER:'postgres',BIPLAN_PG_PASSWORD:password});
  assert.equal(cli.operation,'publish');
  const cliCatalog=await reader.read(cli.publication.publicationId);
  assert.match(cliCatalog.sessions[0].document.text,/^Title: CLI Konseri\nCategory: Konser/);
  assert.ok(cliCatalog.sessions[0].document.lexicalTokens.includes('cli'));
  assert.equal(cliCatalog.sessions[0].document.location.district,'kadikoy');
  const providerState=JSON.parse(await readFile(new URL('./fixtures/biletix.json',import.meta.url),'utf8'));
  const rawBody=Buffer.from(`<script id="ng-state" type="application/json">${JSON.stringify(providerState)}</script>`),rawHash=hash(rawBody);
  const rawRef={sha256:rawHash,key:`bodies/${rawHash}.bin`,bytes:rawBody.length};blobs.set(rawHash,rawBody);
  const rawEnvelope={id:'raw-replay',scope:'partial',horizon:null,inventory:['https://www.biletix.com/etkinlik/5JBD4/ISTANBUL/tr'],pages:[{provider:'biletix',url:'https://www.biletix.com/etkinlik/5JBD4/ISTANBUL/tr',observedAt:'2026-09-09T09:00:00.000Z',rawObjectRef:rawRef,fallbackCategory:'Konser'}]};
  const rawInterrupted=await pipeline.extractCollection(rawEnvelope,{...raw,signal:AbortSignal.abort()});
  assert.equal(rawInterrupted.complete,false);assert.equal(rawInterrupted.processed,0);
  const extracted=await pipeline.extractCollection(rawEnvelope,raw);
  assert.equal(extracted.complete,true);assert.equal(extracted.processed,1);
  const replayedExtract=await pipeline.extractCollection(rawEnvelope,{...raw,extract:()=>{throw new Error('Must reuse extracted output');}});
  assert.equal(replayedExtract.processed,0);assert.equal(replayedExtract.ingestion.replayed,true);
  await writeFile(resolve(rawDirectory,rawRef.key),rawBody);
  const rawFile=resolve(output,'raw-collection.json');await writeFile(rawFile,JSON.stringify({...rawEnvelope,id:'raw-cli'}));
  const rawCli=await runPipeline(['--raw-collection',rawFile,'--raw-directory',rawDirectory,'--publish','--expected-previous',cli.publication.publicationId],{BIPLAN_PG_HOST:'127.0.0.1',BIPLAN_PG_PORT:'15432',BIPLAN_PG_DATABASE:database,BIPLAN_PG_USER:'postgres',BIPLAN_PG_PASSWORD:password});
  assert.equal(rawCli.extraction.complete,true);assert.equal(rawCli.preparation.complete,true);assert.ok(rawCli.publication.publicationId);
  const retained=await createFilesystemRawStore(resolve(output,'fetch-ledger-raw'));
  const originalUrl=rawEnvelope.pages[0].url,responseUrl=`${originalUrl}?redirect=retained`;
  const primaryFetch=await retained.put(rawBody,{url:responseUrl,status:200,fetchedAt:rawEnvelope.pages[0].observedAt,collectorRevision:'fixture-fetch-ledger',headers:{'content-type':'text/html','etag':'original'}});
  const supplementFetch=await retained.put(Buffer.from('{"sessions":[]}'),{url:'https://platform.api.bubilet.com.tr/v2/event/22/city/34/sessions',status:200,fetchedAt:'2026-09-09T09:00:01.000Z',collectorRevision:'fixture-fetch-ledger'});
  const failedFetch=await retained.put(Buffer.from('partial response'),{url:'https://www.bubilet.com.tr/istanbul/etkinlik/failed',status:503,fetchedAt:'2026-09-09T09:00:02.000Z',collectorRevision:'fixture-fetch-ledger',complete:false});
  const emptyFetch=await retained.put(Buffer.alloc(0),{url:'https://biletinial.com/tr-tr/tiyatro/empty',status:204,fetchedAt:'2026-09-09T09:00:03Z',collectorRevision:'fixture-fetch-ledger'});
  const fetches=[primaryFetch,supplementFetch,failedFetch,emptyFetch];
  const ledgerEnvelope={...rawEnvelope,id:'fetch-ledger',fetches,pages:[{...rawEnvelope.pages[0],responseUrl}]};
  const retainedReader={readRaw:ref=>retained.read(ref)};
  const ledgerExtraction=await pipeline.extractCollection(ledgerEnvelope,retainedReader);
  assert.equal(ledgerExtraction.complete,true);
  const savedFetches=(await pool.query('SELECT id,provider,status,complete,fetched_at,receipt_text FROM biplan_pipeline.fetches WHERE id=ANY($1::text[]) ORDER BY fetched_at',[fetches.map(f=>f.fetchId)])).rows;
  assert.equal(savedFetches.length,4);assert.equal(savedFetches[1].provider,'bubilet');assert.equal(savedFetches[2].status,503);assert.equal(savedFetches[2].complete,false);assert.equal(savedFetches[3].status,204);
  assert.deepEqual(savedFetches.map(row=>new Date(row.fetched_at).getTime()),fetches.map(fetch=>Date.parse(fetch.metadata.fetchedAt)));
  assert.equal(JSON.parse(savedFetches[3].receipt_text).fetchedAt,'2026-09-09T09:00:03Z','Original source clock text survives PostgreSQL normalization');
  assert.ok(savedFetches.every(row=>hash(row.receipt_text)===row.id));
  assert.equal((await pool.query('SELECT count(*)::int n FROM biplan_pipeline.fetches WHERE url=$1 AND fetched_at=$2 AND raw_sha256=$3',[responseUrl,primaryFetch.metadata.fetchedAt,rawRef.sha256])).rows[0].n,1,'Exact ledger receipt replaces a synthetic page receipt');
  await assert.rejects(pipeline.extractCollection({...ledgerEnvelope,id:'bad-fetch-hash',fetches:[{...primaryFetch,metadata:{...primaryFetch.metadata,status:500}}]},retainedReader),/identity hash mismatch/);
  const incompletePrimary=await retained.put(rawBody,{url:responseUrl,status:200,fetchedAt:rawEnvelope.pages[0].observedAt,collectorRevision:'fixture-fetch-ledger',complete:false});
  await assert.rejects(pipeline.extractCollection({...ledgerEnvelope,id:'incomplete-fetch',fetches:[incompletePrimary]},retainedReader),/complete successful fetch/);
  await pool.query('UPDATE biplan_pipeline.fetches SET complete=false WHERE id=$1',[primaryFetch.fetchId]);
  await assert.rejects(pipeline.extractCollection({...ledgerEnvelope,id:'conflicting-fetch'},retainedReader),/Immutable fetch receipt conflict/);
  await pool.query('UPDATE biplan_pipeline.fetches SET complete=true WHERE id=$1',[primaryFetch.fetchId]);
  const optionalA=listing('biletix','optional-a','Akustik Gecesi','2027-01-04T18:00:00.000Z'),optionalB=listing('bubilet','optional-b','Bir Akşam Akustik','2027-01-04T18:00:00.000Z');
  const failedJudge=createAmbiguousIdentityJudge({model:'jev-1.13.0',cache:judgmentCache,maxCalls:1,judge:async()=>{throw new Error('Injected optional service failure');}});
  await pipeline.ingestCollection(envelope('optional-failure',[optionalA,optionalB]),raw);
  const optionalPrepared=await pipeline.prepareCollection('optional-failure',{...options,identityVersion:'offline-optional-wrapper-v1',resolveIdentity:async input=>{
    const deterministic=resolveIdentity(input);
    const judged=await failedJudge.evaluate(input[0],input[1],deterministic.listingVenueIds[input[0].listingId],deterministic.listingVenueIds[input[1].listingId]);
    assert.equal(judged.status,'optional_failure');return deterministic;
  }});
  assert.equal(optionalPrepared.complete,true);
  const optionalPublication=await pipeline.publish('optional-failure',{expectedPreviousId:rawCli.publication.publicationId});
  const optionalCatalog=await reader.read(optionalPublication.publicationId);
  assert.equal(optionalCatalog.sessions.length,2,'Optional judgment failure must keep ambiguous pair unmerged');
  assert.ok(optionalCatalog.sessions.every(session=>session.offers.length===1));
  const firstZero={id:'first-zero',scope:'partial',inventory:[emptyFetch.metadata.url],listings:[],rawObjects:[emptyFetch.rawObjectRef],pages:[{url:emptyFetch.metadata.url,provider:'biletinial',status:'verified',observedAt:emptyFetch.metadata.fetchedAt,rawObjectSha256:emptyFetch.rawObjectRef.sha256,listingIds:[]}]};
  await pipeline.ingestCollection(firstZero,retainedReader);await pipeline.prepareCollection(firstZero.id,options);
  const firstZeroReceipt=(await pool.query('SELECT status,reconciliation_required FROM biplan_pipeline.page_receipts WHERE collection_id=$1',[firstZero.id])).rows[0];
  assert.deepEqual(firstZeroReceipt,{status:'verified',reconciliation_required:false},'Never-linked zero remains verified; it does not fabricate retirement');
  const zeroPublication=await pipeline.publish(firstZero.id,{expectedPreviousId:optionalPublication.publicationId});
  const linkedZero={...firstZero,id:'linked-zero',inventory:[optionalA.url],pages:[{url:optionalA.url,provider:optionalA.provider,status:'verified',observedAt:'2026-10-02T13:00:00.000Z',rawObjectSha256:emptyFetch.rawObjectRef.sha256,listingIds:[]}]};
  await pipeline.ingestCollection(linkedZero,retainedReader);await pipeline.prepareCollection(linkedZero.id,options);
  await assert.rejects(pipeline.publish(linkedZero.id,{expectedPreviousId:zeroPublication.publicationId}),/reconciliation requirement/);
  const disappeared=(await pool.query(`SELECT h.withheld,h.reason,l.availability FROM biplan_pipeline.listing_heads h JOIN biplan_pipeline.listings l ON l.revision_id=h.revision_id WHERE h.listing_id=$1`,[optionalA.listingId])).rows[0];
  assert.deepEqual(disappeared,{withheld:true,reason:'negative_zero_page',availability:'available'},'Disappearance withholds evidence without inventing cancellation');
  const optionalSelected=optionalCatalog.sessions.flatMap(session=>session.offers.filter(offer=>offer.listingId===optionalA.listingId).map(offer=>({sessionId:session.id,offerId:offer.id,offerRevisionId:offer.revisionId})));
  assert.equal((await reader.revalidate(optionalPublication.publicationId,optionalSelected,'2026-10-02T13:30:00.000Z'))[0].usable,false);
  const restoredA=listing('biletix','optional-a','Akustik Gecesi','2027-01-04T18:00:00.000Z','2026-10-02T14:00:00.000Z');
  await pipeline.ingestCollection(envelope('restored-after-zero',[restoredA,optionalB]),raw);await pipeline.prepareCollection('restored-after-zero',options);
  const restoredPublication=await pipeline.publish('restored-after-zero',{expectedPreviousId:zeroPublication.publicationId});
  const restoredCatalog=await reader.read(restoredPublication.publicationId);
  const restoredSelected=restoredCatalog.sessions.flatMap(session=>session.offers.filter(offer=>offer.listingId===restoredA.listingId).map(offer=>({sessionId:session.id,offerId:offer.id,offerRevisionId:offer.revisionId})));
  assert.equal((await reader.revalidate(restoredPublication.publicationId,restoredSelected,'2026-10-02T14:30:00.000Z'))[0].usable,true);
  const evidence={evidence:'pipeline-postgres-integration',database,firstPublication:pinned,secondPublication:second.publicationId,cliPublication:cli.publication.publicationId,rawCliPublication:rawCli.publication.publicationId,optionalFailurePublication:optionalPublication.publicationId,restoredAfterZeroPublication:restoredPublication.publicationId,unchangedExtractionCalls:replayedExtract.processed,changedCounts:{...changedResult.counts,normalize:bounded.counts.normalize},interruptedResume:true,offlineJudgments,durableJudgmentCacheRows:3,retainedFetchLedgerRows:savedFetches.length,negativeZeroPageWithholding:true,realRuntimeSourceInvalidation:true,externalCalls:0};
  await writeFile(resolve(output,'receipt.json'),JSON.stringify(evidence,null,2));
  console.log(JSON.stringify(evidence));
});
